# Site settings
title: EİSTATİSTİK
email:
description: Veri analizinin ne kadar önemli olduğunu biliyoruz. İstatistik alanındaki uzmanlığımızı sizinle paylaşma adına buradayız. Veri analizinde doğru sonuç EİSTATİSTİK ile bir adım önde.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
# url: "https://eistatistik.github.io/" # the base hostname & protocol for your site
url: "https://statistic.academic.support/" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
# data-ad-slot: 2973388149
# data-ad-client: ca-pub-9204963049240271
# google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-89117195-1"
addthis_id: ra-5855a894d8309ae3
# disqus_account: jeky-new-age

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/naci_murat
  - title: facebook
    url: https://facebook.com/eistatistik
  #- title: google-plus
  #  url: https://plus.google.com/+AntoniotrentoIt
  - title: github
    url: http://github.com/eistatistik

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
